clear all;
close all;
clc;
[im,map] = imread(".\PICTO\01.png");
[sizex, sizey, sizez] = size(im);
figure(1);
imshow(im);
im = rgb2hsv(im);
%im = rgb2gray(im);
figure(2);
imshow(im);
%figure(3);
%imhist(im);